In [1]:
import pandas as pd
import numpy as np
import warnings
from sklearn.linear_model import LogisticRegression
from sklearn.externals import joblib

warnings.simplefilter("ignore")

In [2]:
df_new = pd.read_csv('New Matches API.csv', header = 0)
df_team = pd.read_csv('team.csv',header = 0)
df_player = pd.read_csv('player.csv',header = 0)

In [3]:
df_predict = pd.DataFrame(columns = ['home_team_goals_difference','away_team_goals_difference','games_won_home_team','games_won_away_team','games_against_won','games_against_lost','League_21518.0','League_24558.0','home_player_1_overall_rating','home_player_2_overall_rating','home_player_3_overall_rating','home_player_4_overall_rating','home_player_5_overall_rating','home_player_6_overall_rating','home_player_7_overall_rating','home_player_8_overall_rating','home_player_9_overall_rating','home_player_10_overall_rating','home_player_11_overall_rating','away_player_1_overall_rating','away_player_2_overall_rating','away_player_3_overall_rating','away_player_4_overall_rating','away_player_5_overall_rating','away_player_6_overall_rating','away_player_7_overall_rating','away_player_8_overall_rating','away_player_9_overall_rating','away_player_10_overall_rating','away_player_11_overall_rating','B365_Win','B365_Draw','B365_Defeat','BW_Win','BW_Draw','BW_Defeat'])

In [4]:
ht = df_team.team_api_id[df_team['team_long_name']=='Man United'].values[0]
at = df_team.team_api_id[df_team['team_long_name']=='Chelsea'].values[0]

h1 = 'De Gea'
h2 = 'L. Shaw'
h3 = 'C. Smalling'
h4 = 'E. Bailly'
h5 = 'A. Valencia'
h6 = 'M. Rashford'
h7 = 'Juan Mata'
h8 = 'P. Pogba'
h9 = 'A. Martial'
h10 = 'Ander Herrera'
h11 = 'R. Lukaku'

a1 = 'L. Karius'
a2 = 'N. Clyne'
a3 = 'J. Matip'
a4 = 'V. van Dijk'
a5 = 'J. Milner'
a6 = 'E. Can'
a7 = 'A. Lallana'
a8 = 'J. Henderson'
a9 = 'G. Wijnaldum'
a10 = 'M. Salah'
a11 = 'Roberto Firmino'

In [5]:
df_predict.loc[0,'B365_Win'] = 0.42
df_predict.loc[0,'B365_Draw'] = 0.23
df_predict.loc[0,'B365_Defeat'] = 0.35

df_predict.loc[0,'BW_Win'] = 0.44
df_predict.loc[0,'BW_Draw'] = 0.26
df_predict.loc[0,'BW_Defeat'] = 0.30

df_predict.loc[0,'League_21518.0'] = 1
df_predict.loc[0,'League_24558.0'] = 0

In [6]:
#df_predict = pd.DataFrame(columns = ['home_team_goals_difference','away_team_goals_difference','games_won_home_team','games_won_away_team','games_against_won','games_against_lost','League_21518.0','League_24558.0','home_player_1_overall_rating','home_player_2_overall_rating','home_player_3_overall_rating','home_player_4_overall_rating','home_player_5_overall_rating','home_player_6_overall_rating','home_player_7_overall_rating','home_player_8_overall_rating','home_player_9_overall_rating','home_player_10_overall_rating','home_player_11_overall_rating','away_player_1_overall_rating','away_player_2_overall_rating','away_player_3_overall_rating','away_player_4_overall_rating','away_player_5_overall_rating','away_player_6_overall_rating','away_player_7_overall_rating','away_player_8_overall_rating','away_player_9_overall_rating','away_player_10_overall_rating','away_player_11_overall_rating','B365_Win','B365_Draw','B365_Defeat','BW_Win','BW_Draw','BW_Defeat'])

In [7]:
home_player_1_overall_rating = df_player.Overall[df_player.player_name==h1]
home_player_2_overall_rating = df_player.Overall[df_player.player_name==h2]
home_player_3_overall_rating = df_player.Overall[df_player.player_name==h3]
home_player_4_overall_rating = df_player.Overall[df_player.player_name==h4]
home_player_5_overall_rating = df_player.Overall[df_player.player_name==h5]
home_player_6_overall_rating = df_player.Overall[df_player.player_name==h6]
home_player_7_overall_rating = df_player.Overall[df_player.player_name==h7]
home_player_8_overall_rating = df_player.Overall[df_player.player_name==h8]
home_player_9_overall_rating = df_player.Overall[df_player.player_name==h9]
home_player_10_overall_rating = df_player.Overall[df_player.player_name==h10]
home_player_11_overall_rating = df_player.Overall[df_player.player_name==h11]

away_player_1_overall_rating = df_player.Overall[df_player.player_name==a1]
away_player_2_overall_rating = df_player.Overall[df_player.player_name==a2]
away_player_3_overall_rating = df_player.Overall[df_player.player_name==a3]
away_player_4_overall_rating = df_player.Overall[df_player.player_name==a4]
away_player_5_overall_rating = df_player.Overall[df_player.player_name==a5]
away_player_6_overall_rating = df_player.Overall[df_player.player_name==a6]
away_player_7_overall_rating = df_player.Overall[df_player.player_name==a7]
away_player_8_overall_rating = df_player.Overall[df_player.player_name==a8]
away_player_9_overall_rating = df_player.Overall[df_player.player_name==a9]
away_player_10_overall_rating = df_player.Overall[df_player.player_name==a10]
away_player_11_overall_rating = df_player.Overall[df_player.player_name==a11]

In [8]:
df_predict.loc[0,'home_player_1_overall_rating'] = df_player.Overall[df_player.player_name==h1].values[0]
df_predict.loc[0,'home_player_2_overall_rating'] = df_player.Overall[df_player.player_name==h2].values[0]
df_predict.loc[0,'home_player_3_overall_rating'] = df_player.Overall[df_player.player_name==h3].values[0]
df_predict.loc[0,'home_player_4_overall_rating'] = df_player.Overall[df_player.player_name==h4].values[0]
df_predict.loc[0,'home_player_5_overall_rating'] = df_player.Overall[df_player.player_name==h5].values[0]
df_predict.loc[0,'home_player_6_overall_rating'] = df_player.Overall[df_player.player_name==h6].values[0]
df_predict.loc[0,'home_player_7_overall_rating'] = df_player.Overall[df_player.player_name==h7].values[0]
df_predict.loc[0,'home_player_8_overall_rating'] = df_player.Overall[df_player.player_name==h8].values[0]
df_predict.loc[0,'home_player_9_overall_rating'] = df_player.Overall[df_player.player_name==h9].values[0]
df_predict.loc[0,'home_player_10_overall_rating'] = df_player.Overall[df_player.player_name==h10].values[0]
df_predict.loc[0,'home_player_11_overall_rating'] = df_player.Overall[df_player.player_name==h11].values[0]

df_predict.loc[0,'away_player_1_overall_rating'] = df_player.Overall[df_player.player_name==a1].values[0]
df_predict.loc[0,'away_player_2_overall_rating'] = df_player.Overall[df_player.player_name==a2].values[0]
df_predict.loc[0,'away_player_3_overall_rating'] = df_player.Overall[df_player.player_name==a3].values[0]
df_predict.loc[0,'away_player_4_overall_rating'] = df_player.Overall[df_player.player_name==a4].values[0]
df_predict.loc[0,'away_player_5_overall_rating'] = df_player.Overall[df_player.player_name==a5].values[0]
df_predict.loc[0,'away_player_6_overall_rating'] = df_player.Overall[df_player.player_name==a6].values[0]
df_predict.loc[0,'away_player_7_overall_rating'] = df_player.Overall[df_player.player_name==a7].values[0]
df_predict.loc[0,'away_player_8_overall_rating'] = df_player.Overall[df_player.player_name==a8].values[0]
df_predict.loc[0,'away_player_9_overall_rating'] = df_player.Overall[df_player.player_name==a9].values[0]
df_predict.loc[0,'away_player_10_overall_rating'] = df_player.Overall[df_player.player_name==a10].values[0]
df_predict.loc[0,'away_player_11_overall_rating'] = df_player.Overall[df_player.player_name==a11].values[0]

In [9]:
df_predict

,home_team_goals_difference,away_team_goals_difference,games_won_home_team,games_won_away_team,games_against_won,games_against_lost,League_21518.0,League_24558.0,home_player_1_overall_rating,home_player_2_overall_rating,...,away_player_8_overall_rating,away_player_9_overall_rating,away_player_10_overall_rating,away_player_11_overall_rating,B365_Win,B365_Draw,B365_Defeat,BW_Win,BW_Draw,BW_Defeat
0,NaN,NaN,NaN,NaN,NaN,NaN,1,0,91,78,...,81,82,87,85,0.42,0.23,0.35,0.44,0.26,0.3

In [10]:
df_new.drop('Unnamed: 0',axis=1, inplace = True)

In [11]:
def get_match_features(match, matches, x = 10):
    ''' Create match specific features for a given match. '''
    
    print('In get_match_features')
    
    #Define variables
    date = match.date
    home_team = match.home_team_api_id
    away_team = match.away_team_api_id
    
    print(date,home_team,away_team)
    
    #Get last x matches of home and away team
    matches_home_team = get_last_matches(matches, date, home_team, x = 10)
    matches_away_team = get_last_matches(matches, date, away_team, x = 10)
    
    #Get last x matches of both teams against each other
    last_matches_against = get_last_matches_against_eachother(matches, date, home_team, away_team, x = 2)
    
    #Create goal variables
    home_goals = get_goals(matches_home_team, home_team)
    away_goals = get_goals(matches_away_team, away_team)
    home_goals_conceided = get_goals_conceided(matches_home_team, home_team)
    away_goals_conceided = get_goals_conceided(matches_away_team, away_team)
    
    #Define result data frame
    result = pd.DataFrame()
    
    #Define ID features
    #result.loc[0, 'match_api_id'] = match.match_api_id
    #result.loc[0, 'league_id'] = match.league_id

    #Create match features
    result.loc[0, 'home_team_goals_difference'] = home_goals - home_goals_conceided
    result.loc[0, 'away_team_goals_difference'] = away_goals - away_goals_conceided
    result.loc[0, 'games_won_home_team'] = get_wins(matches_home_team, home_team) 
    result.loc[0, 'games_won_away_team'] = get_wins(matches_away_team, away_team)
    result.loc[0, 'games_against_won'] = get_wins(last_matches_against, home_team)
    result.loc[0, 'games_against_lost'] = get_wins(last_matches_against, away_team)
    
    #Return match features
    return result.loc[0]

def get_last_matches(matches, date, team, x = 10):
    ''' Get the last x matches of a given team. '''
    
    print('In get_last_matches')
    
    #Filter team matches from matches
    team_matches = matches[(matches['home_team_api_id'] == team) | (matches['away_team_api_id'] == team)]
                           
    #Filter x last matches from team matches
    last_matches = team_matches[team_matches.date < date].sort_values(by = 'date', ascending = False).iloc[0:x,:]
    
    #Return last matches
    return last_matches

def get_last_matches_against_eachother(matches, date, home_team, away_team, x = 10):
    ''' Get the last x matches of two given teams. '''
    
    print('In get_last_matches_against_eachother')
    
    #Find matches of both teams
    home_matches = matches[(matches['home_team_api_id'] == home_team) & (matches['away_team_api_id'] == away_team)]    
    away_matches = matches[(matches['home_team_api_id'] == away_team) & (matches['away_team_api_id'] == home_team)]  
    total_matches = pd.concat([home_matches, away_matches])
    
    #Get last x matches
    try:    
        last_matches = total_matches[total_matches.date < date].sort_values(by = 'date', ascending = False).iloc[0:x,:]
    except:
        last_matches = total_matches[total_matches.date < date].sort_values(by = 'date', ascending = False).iloc[0:total_matches.shape[0],:]
        
        #Check for error in data
        if(last_matches.shape[0] > x):
            print("Error in obtaining matches")
            
    #Return data
    return last_matches

def get_goals(matches, team):
    ''' Get the goals of a specfic team from a set of matches. '''
    
    print('In get_goals')
    
    #Find home and away goals
    home_goals = int(matches.home_team_goal[matches.home_team_api_id == team].sum())
    away_goals = int(matches.away_team_goal[matches.away_team_api_id == team].sum())

    total_goals = home_goals + away_goals
    
    #Return total goals
    return total_goals

def get_goals_conceided(matches, team):
    ''' Get the goals conceided of a specfic team from a set of matches. '''

    print('In get_goals_conceded')
    
    #Find home and away goals
    home_goals = int(matches.home_team_goal[matches.away_team_api_id == team].sum())
    away_goals = int(matches.away_team_goal[matches.home_team_api_id == team].sum())

    total_goals = home_goals + away_goals

    #Return total goals
    return total_goals

def get_wins(matches, team):
    ''' Get the number of wins of a specfic team from a set of matches. '''
    
    print('In get_wins')
    
    #Find home and away wins
    home_wins = int(matches.home_team_goal[(matches.home_team_api_id == team) & (matches.home_team_goal > matches.away_team_goal)].count())
    away_wins = int(matches.away_team_goal[(matches.away_team_api_id == team) & (matches.away_team_goal > matches.home_team_goal)].count())

    total_wins = home_wins + away_wins

    #Return total wins
    return total_wins

In [12]:
df_new = df_new.append({'home_team_api_id':ht, 'away_team_api_id':at, 'date':'25-04-2018'}, ignore_index = True)

In [13]:
df_new.sort_index(inplace=True)

In [14]:
match = df_new.iloc[-1,:]

In [15]:
df_new[(df_new['home_team_api_id'] == 10260) | (df_new['away_team_api_id'] == 10260)]

,date,HomeTeam,AwayTeam,home_team_goal,away_team_goal,home_team_api_id,away_team_api_id
8,13-08-2017,Man United,West Ham,4.0,0.0,10260.0,8654.0
16,19-08-2017,Swansea,Man United,0.0,4.0,10003.0,10260.0
23,26-08-2017,Man United,Leicester,2.0,0.0,10260.0,8197.0
36,09-09-2017,Stoke,Man United,2.0,2.0,10194.0,10260.0
49,17-09-2017,Man United,Everton,4.0,0.0,10260.0,8668.0
54,23-09-2017,Southampton,Man United,0.0,1.0,8466.0,10260.0
63,30-09-2017,Man United,Crystal Palace,4.0,0.0,10260.0,9826.0
72,14-10-2017,Liverpool,Man United,0.0,0.0,8650.0,10260.0
82,21-10-2017,Huddersfield,Man United,2.0,1.0,10260.0,10260.0
94,28-10-2017,Man United,Tottenham,1.0,0.0,10260.0,8586.0
106,05-11-2017,Chelsea,Man United,1.0,0.0,8455.0,10260.0
116,18-11-2017,Man United,Newcastle,4.0,1.0,10260.0,NaN
123,25-11-2017,Man United,Brighton,1.0,0.0,10260.0,NaN
132,28-11-2017,Watford,Man United,2.0,4.0,9817.0,10260.0
140,02-12-2017,Arsenal,Man United,1.0,3.0,9825.0,10260.0
158,10-12-2017,Man United,Man City,1.0,2.0,10260.0,8456.0
164,13-12-2017,Man United,Bournemouth,1.0,0.0,10260.0,8678.0
178,17-12-2017,West Brom,Man United,1.0,2.0,8659.0,10260.0
184,23-12-2017,Leicester,Man United,2.0,2.0,8197.0,10260.0
194,26-12-2017,Man United,Burnley,2.0,2.0,10260.0,8191.0
204,30-12-2017,Man United,Southampton,0.0,0.0,10260.0,8466.0
211,01-01-2018,Everton,Man United,0.0,2.0,8668.0,10260.0
229,15-01-2018,Man United,Stoke,3.0,0.0,10260.0,10194.0
232,20-01-2018,Burnley,Man United,0.0,1.0,8191.0,10260.0
249,31-01-2018,Tottenham,Man United,2.0,0.0,8586.0,10260.0
255,03-02-2018,Man United,Huddersfield,2.0,0.0,10260.0,NaN
267,11-02-2018,Newcastle,Man United,1.0,0.0,10260.0,10260.0
278,25-02-2018,Man United,Chelsea,2.0,1.0,10260.0,8455.0
289,05-03-2018,Crystal Palace,Man United,2.0,3.0,9826.0,10260.0
293,10-03-2018,Man United,Liverpool,2.0,1.0,10260.0,8650.0
...,...,...,...,...,...,...,...
435,29-10-2016,Man United,Burnley,0.0,0.0,10260.0,8191.0
453,06-11-2016,Swansea,Man United,1.0,3.0,10003.0,10260.0
456,19-11-2016,Man United,Arsenal,1.0,1.0,10260.0,9825.0
471,27-11-2016,Man United,West Ham,1.0,1.0,10260.0,8654.0
482,04-12-2016,Everton,Man United,1.0,1.0,8668.0,10260.0
492,11-12-2016,Man United,Tottenham,1.0,0.0,10260.0,8586.0
496,14-12-2016,Crystal Palace,Man United,1.0,2.0,9826.0,10260.0
508,17-12-2016,West Brom,Man United,0.0,2.0,8659.0,10260.0
519,26-12-2016,Man United,Sunderland,3.0,1.0,10260.0,8472.0
529,31-12-2016,Man United,Middlesbrough,2.0,1.0,10260.0,8549.0
539,02-01-2017,West Ham,Man United,0.0,2.0,8654.0,10260.0
553,15-01-2017,Man United,Liverpool,1.0,1.0,10260.0,8650.0
559,21-01-2017,Stoke,Man United,1.0,1.0,10194.0,10260.0
571,01-02-2017,Man United,Hull,0.0,0.0,10260.0,8667.0
582,05-02-2017,Leicester,Man United,0.0,3.0,8197.0,10260.0
586,11-02-2017,Man United,Watford,2.0,0.0,10260.0,9817.0
604,04-03-2017,Man United,Bournemouth,1.0,1.0,10260.0,8678.0
625,19-03-2017,Middlesbrough,Man United,1.0,3.0,8549.0,10260.0
632,01-04-2017,Man United,West Brom,0.0,0.0,10260.0,8659.0
639,04-04-2017,Man United,Everton,1.0,1.0,10260.0,8668.0
655,09-04-2017,Sunderland,Man United,0.0,3.0,8472.0,10260.0
664,16-04-2017,Man United,Chelsea,2.0,0.0,10260.0,8455.0
671,23-04-2017,Burnley,Man United,0.0,2.0,8191.0,10260.0
677,27-04-2017,Man City,Man United,0.0,0.0,8456.0,10260.0
684,30-04-2017,Man United,Swansea,1.0,1.0,10260.0,10003.0
695,07-05-2017,Arsenal,Man United,2.0,0.0,9825.0,10260.0
707,14-05-2017,Tottenham,Man United,2.0,1.0,8586.0,10260.0
712,17-05-2017,Southampton,Man United,0.0,0.0,8466.0,10260.0
720,21-05-2017,Man United,Crystal Palace,2.0,0.0,10260.0,9826.0
2029,25-04-2018,NaN,NaN,NaN,NaN,10260.0,8455.0

In [16]:
get_last_matches(df_new, '25-04-2018', 10260, x = 10)

In get_last_matches

,date,HomeTeam,AwayTeam,home_team_goal,away_team_goal,home_team_api_id,away_team_api_id
278,25-02-2018,Man United,Chelsea,2.0,1.0,10260.0,8455.0
397,24-09-2016,Man United,Leicester,4.0,1.0,10260.0,8197.0
184,23-12-2017,Leicester,Man United,2.0,2.0,8197.0,10260.0
432,23-10-2016,Chelsea,Man United,4.0,0.0,8455.0,10260.0
54,23-09-2017,Southampton,Man United,0.0,1.0,8466.0,10260.0
671,23-04-2017,Burnley,Man United,0.0,2.0,8191.0,10260.0
82,21-10-2017,Huddersfield,Man United,2.0,1.0,10260.0,10260.0
720,21-05-2017,Man United,Crystal Palace,2.0,0.0,10260.0,9826.0
559,21-01-2017,Stoke,Man United,1.0,1.0,10194.0,10260.0
232,20-01-2018,Burnley,Man United,0.0,1.0,8191.0,10260.0

In [17]:
match_stats = get_match_features(match, df_new, x = 10)

In get_match_features
25-04-2018 10260.0 8455.0
In get_last_matches
In get_last_matches
In get_last_matches_against_eachother
In get_goals
In get_goals
In get_goals_conceded
In get_goals_conceded
In get_wins
In get_wins
In get_wins
In get_wins

In [18]:
match_stats

home_team_goals_difference     6.0
away_team_goals_difference    16.0
games_won_home_team            7.0
games_won_away_team            7.0
games_against_won              1.0
games_against_lost             1.0
Name: 0, dtype: float64

In [19]:
df_predict.loc[0,'home_team_goals_difference'] = match_stats.home_team_goals_difference
df_predict.loc[0,'away_team_goals_difference'] = match_stats.away_team_goals_difference
df_predict.loc[0,'games_won_home_team'] = match_stats.games_won_home_team
df_predict.loc[0,'games_won_away_team'] = match_stats.games_won_away_team
df_predict.loc[0,'games_against_won'] = match_stats.games_against_won
df_predict.loc[0,'games_against_lost'] = match_stats.games_against_lost

In [20]:
df_predict

,home_team_goals_difference,away_team_goals_difference,games_won_home_team,games_won_away_team,games_against_won,games_against_lost,League_21518.0,League_24558.0,home_player_1_overall_rating,home_player_2_overall_rating,...,away_player_8_overall_rating,away_player_9_overall_rating,away_player_10_overall_rating,away_player_11_overall_rating,B365_Win,B365_Draw,B365_Defeat,BW_Win,BW_Draw,BW_Defeat
0,6,16,7,7,1,1,1,0,91,78,...,81,82,87,85,0.42,0.23,0.35,0.44,0.26,0.3

In [21]:
clf = joblib.load('LogisticRegression.pkl')

In [22]:
clf.predict_proba(df_predict)

array([[ 0.18255084,  0.45100308,  0.36644608]])

In [23]:
clf.classes_

array(['Defeat', 'Draw', 'Win'], dtype=object)